<?php
// BEGIN HOSTED-SOLUTIONS DEPLOYMENT SCRIPTS MANAGED BLOCK

// the content here is generated by update_config_overrule.py

// END HOSTED-SOLUTIONS DEPLOYMENT SCRIPTS MANAGED BLOCK
/**
 * This file is used to overrule default settings of any config file in Enterprise.
 * Overruling configurations is possible for any setting that is contained within a block of the format:
 *
 * if( !defined('<SETTING_NAME>') ) {
 *    ...
 * }
 *
 */

/**
 * Logging
 */
define('LOGFILE_FORMAT', 'plain');
define('OUTPUTDIRECTORY', '/Logs/');
define ('DEBUGLEVELS', serialize( array(
    'default' => 'NONE'
)));

/**
 * All additional logging will be disabled by default
 */
define( 'PROFILELEVEL', 0 );
define( 'LOGSQL', false );
define( 'LOG_INTERNAL_SERVICES', false );
define( 'LOG_DPS_SERVICES', false );
define( 'LOG_RABBITMQ_SERVICES', false );
define( 'SERVICE_VALIDATION', false );
define( 'LOGLEVEL', '0' );

/**
 * Solr
 */
define ('SOLR_TIMEOUT', 50);

/**
 * Aurora
 */
if( file_exists( BASEDIR.'/config/plugins/ContentStation/backwards_compat_es.php' ) ) {
   require_once BASEDIR.'/config/plugins/ContentStation/backwards_compat_es.php';
}

define( 'CS_DIGITAL_EDITOR_ENABLED', true );

/**
 * Email
 */
if( getenv("SMTP_HOSTNAME") && getenv("SMTP_USERNAME") && getenv("SMTP_PASSWORD_ENCODED") && getenv("SMTP_DOMAIN") ) {
    $domain = rtrim( getenv("SMTP_DOMAIN"), '.' );

    define ('EMAIL_SMTP', getenv("SMTP_HOSTNAME"));
    define ('EMAIL_SMTP_USER', getenv("SMTP_USERNAME"));
    define ('EMAIL_SMTP_PASS', getenv("SMTP_PASSWORD_ENCODED"));
    define ('EMAIL_PORT', 587);
    define ('EMAIL_SSL', 'tls');
    define ('EMAIL_SENDER_ADDRESS', "noreply@{$domain}");
    define ('EMAIL_SENDER_NAME', 'Enterprise Server');
}

/**
 * Set the FILE_TRANSFER_LOCAL_PATH and WEBEDITDIR so that it's not included in the FileStore
 */
define( 'FILE_TRANSFER_LOCAL_PATH', '/TransferServerCache' );
define( 'WEBEDITDIR', '/WebEdit/' );

/**
 * Server Features
 */
if( !defined('SERVERFEATURES') ) {
    define ('SERVERFEATURES', serialize(array(
        new Feature( 'Messaging' ),
        new Feature( 'EventPort' , 8093 ),
        new Feature( 'CompanyLanguage' , 'enUS'),
        new Feature( 'KeepCheckedOut' ),
    )));
}

if( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' ) {
    define('SERVERURL_ROOT', $_SERVER['HTTP_X_FORWARDED_PROTO'] . '://' . $_SERVER['HTTP_HOST'] . (($_SERVER['HTTP_X_FORWARDED_PORT'] != 443) ? $_SERVER['HTTP_X_FORWARDED_PORT'] : ''));
}

define( 'WEBEDITDIRIDSERV', 'C:/WoodWing/WebEdit/' );

/**
 * Import the container default settings
 */
if( file_exists( BASEDIR.'/config/container_defaults.php' ) ) {
    require_once BASEDIR.'/config/container_defaults.php';
}

